"""Local-first primitives for auditable focus experiments."""

from .domain import (
    AbandonReason,
    BreakCompleted,
    BreakStarted,
    DomainEvent,
    FocusCompleted,
    FocusStarted,
    InterruptionKind,
    InterruptionRecorded,
    InvalidEvent,
    InvalidTransition,
    SessionAbandoned,
    SessionPhase,
    SessionPlanned,
    SessionState,
    apply_event,
    reduce_events,
)
from .storage import (
    CorruptJournal,
    JournalConflict,
    JournalError,
    JournalSecurityError,
    JournalVerification,
    SQLiteEventStore,
    default_journal_path,
)

__all__ = [
    "AbandonReason",
    "BreakCompleted",
    "BreakStarted",
    "CorruptJournal",
    "DomainEvent",
    "FocusCompleted",
    "FocusStarted",
    "InterruptionKind",
    "InterruptionRecorded",
    "InvalidEvent",
    "InvalidTransition",
    "JournalConflict",
    "JournalError",
    "JournalSecurityError",
    "JournalVerification",
    "SQLiteEventStore",
    "SessionAbandoned",
    "SessionPhase",
    "SessionPlanned",
    "SessionState",
    "apply_event",
    "default_journal_path",
    "reduce_events",
]
